POST http://localhost:3001/users
Content-Type: application/json

{
    "nome": "Paula",
    "idade": "39"
}

###

GET http://localhost:3001/users


###

PUT http://localhost:3001/users/2
Content-Type: application/json

{
    "nome": "Bia",
    "idade": "8"
}

###

DELETE http://localhost:3001/users/3
